
POST http://localhost:4000/thread HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiYzVlMjkwYTUtN2ZhYy00YzYwLTkxODctYWU5NWM5YmE3YWVjIiwiaWF0IjoxNzQ2MDg3NzE2LCJleHAiOjE3NDYxMjM3MTZ9.GstCUtuw_USPZ9Zpoih_04By1JBBUy0amHChT5I-YCg

{
    "title": "9",
    "prompt": "hello "
}

###
POST http://localhost:4000/thread/d5bd905d-eb36-43be-b426-f3812a75d8a3/continue HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiYzVlMjkwYTUtN2ZhYy00YzYwLTkxODctYWU5NWM5YmE3YWVjIiwiaWF0IjoxNzQ2MDg3NzE2LCJleHAiOjE3NDYxMjM3MTZ9.GstCUtuw_USPZ9Zpoih_04By1JBBUy0amHChT5I-YCg

{
    "prompt": "what is your name?"
}

###
GET  http://localhost:4000/thread HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiYzVlMjkwYTUtN2ZhYy00YzYwLTkxODctYWU5NWM5YmE3YWVjIiwiaWF0IjoxNzQ2MDg3NzE2LCJleHAiOjE3NDYxMjM3MTZ9.GstCUtuw_USPZ9Zpoih_04By1JBBUy0amHChT5I-YCg

###
POST  http://localhost:4000/thread/print HTTP/1.1
content-type: application/json


###
GET  http://localhost:4000/thread/05e5af79-790b-4dff-94a6-9cfc73fe23a0 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiYzVlMjkwYTUtN2ZhYy00YzYwLTkxODctYWU5NWM5YmE3YWVjIiwiaWF0IjoxNzQ2MDg3NzE2LCJleHAiOjE3NDYxMjM3MTZ9.GstCUtuw_USPZ9Zpoih_04By1JBBUy0amHChT5I-YCg


###
GET  http://localhost:4000/thread/ec113818-ab48-4a5b-9d9d-ac3cb8a05687/message HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbXBsZSIsImlkIjoiYzVlMjkwYTUtN2ZhYy00YzYwLTkxODctYWU5NWM5YmE3YWVjIiwiaWF0IjoxNzQ1OTExNTg2LCJleHAiOjE3NDU5NDc1ODZ9.hDjaw3Fuk2WtU7mmFSftsCLQbXnqazsLZHCahS_XKUs



###
GET  http://localhost:4000/thread/7487b2b5-f9a9-4a43-8ab2-05d65f151ee7/message HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyZmFuIiwiaWQiOiJhYzVjMTVkYi01ZjFlLTQ2MDgtOGZlZC1hODA0M2UwYjE4YWUiLCJpYXQiOjE3NDU5MTY4NTksImV4cCI6MTc0NTk1Mjg1OX0.2u_LzbwFzfTvLRUma63NZbTWKDmq7goYKWvNtSyQbFA

